### ISSUE TITLE
[1.21.1] Console error in 0.1.7

### ISSUE THREAD

**Issue by rfin0** [pietro-lopes/AllTheLeaks#10]
I updated the mod to version 0.1.7, I launch my main mod build on NeoForge 21.1.80 1.21.1 for testing and I notice this interesting error, which I was able to repeat without other mods:
Logs (server): https://mclo.gs/HYqbRK0 & Logs (client): https://mclo.gs/iUyGfdk
Debug (server): https://mclo.gs/6dCrXka
It does not cause the server/client to crash.

Before the update (on version 0.1.6) there was no such error.
(Server 0.1.6: logs - https://mclo.gs/9JELZKT & debug - https://mclo.gs/rvMLcFa).

**Comment by pietro-lopes** [comment]
Thanks for the report, new version is uploading on CurseForge :+1:
