### ISSUE TITLE
main.GenericRecipeMixin not functional

### ISSUE THREAD

**Issue by ghost** [pietro-lopes/AllTheLeaks#12]
Suggest to either remove the mixin or disable it by version range
See line 2352 of https://mclo.gs/Qg2a6fH , this is also present in all logs submitted to us for other issues.

**Comment by pietro-lopes** [comment]
Yes, also noticed that when I opened that report and did the change locally (added range upto 1.1.814)

👍

**Comment by alekthefirst** [comment]
Awesome

**Comment by ghost** [comment]
Awesome
