### ISSUE TITLE
JourneyMap fixes

### ISSUE THREAD

**Issue by mysticdrew** [pietro-lopes/AllTheLeaks#15]
beta.33 will address all the things you have done. 
Though, I would have fixed them right away if you would have reported the issues to me, they were quite trivial.

However, I do have a question about this. 
https://github.com/pietro-lopes/AllTheLeaks/blob/3740bccd5cde3163bb5dcaf8cff794569c6b4d94/src/main/java/dev/uncandango/alltheleaks/mixin/core/main/PlayerDataMixin.java#L31

Why is this needed? I see some issues as that event is fired when a player dies, so this will clear their setting when they die.

**Comment by pietro-lopes** [comment]
I do report *some* when I can, as i did with other report, but when source is closed it gets more difficult to report.

As for the mixin on PlayerData, when a player died, that map was storing a dead instance of the player, the this.getPlayer rebuild it. If this rebuild make a player lose its previous setting somehow, I'm afraid you need to refactor this to not store a dead instance of player and preserve the previous settings.

**Comment by mysticdrew** [comment]
I only maintain the uuid of the  ServerPlayer. Not the ServerPlayer instance anywhere.

**Comment by pietro-lopes** [comment]
`Map<String, PlayerData.Player> playerMap;`

Please check if PlayerData.Player stores ServerPlayer by any chance, I can't check right now

**Comment by mysticdrew** [comment]
it does not, only the uuid
![image](https://github.com/user-attachments/assets/6fa8e875-6e63-45e7-a57a-9e827a57db00)

**Comment by pietro-lopes** [comment]
I see, I would need access to my stuff to check at what point/version that was based on.

If that currently is not needed just ignore as I will remove or restrict to the point it was needed.

For the others I will restrict those fixes to apply only to versions before beta.33

**Comment by mysticdrew** [comment]
I am renaming it to PlayerDTO to remove confusion and making it its own class instead of a nested static class. 
The comparator mixins you have, I fixed so those will no longer be needed in beta.33. 
Please let me know if you run into any more issues in the future so I can get them addressed right away. 

Thanks!
