### ISSUE TITLE
Could u diagnose this modpack for leaks?

### ISSUE THREAD

**Issue by Cixon** [pietro-lopes/AllTheLeaks#2]
https://modrinth.com/modpack/project-4j

**Comment by pietro-lopes** [comment]
I can send you the mod (not released yet, still need to add some more features) that I use for you to test in your instance if you want.
Just hop into ATM Discord and @ me and I send you the jar.

**Comment by pietro-lopes** [comment]
As we already talked in Discord, I'm closing this issue.
