### ISSUE TITLE
Zenscript error? 

### ISSUE THREAD

**Issue by BiakCeu** [pietro-lopes/AllTheLeaks#4]
![Screenshot 2024-11-08 231155](https://github.com/user-attachments/assets/c828032b-3384-4887-80b2-b1718c1b9641)

Playing custom modpack. 
Forge 1.20.1 
Forge 47.3.10

**Comment by pietro-lopes** [comment]
Interesting, can you share an export, so I can test?
meanwhile you can turn off ingredient dedupe in `config/alltheleaks.json`

**Comment by pietro-lopes** [comment]
Pushed a version with that feature off by default, just use that, I found other incompatibilities with other JEI Plugins that are modifying the ItemStack of the ingredients directly causing visual bug

**Comment by BiakCeu** [comment]
Ah alright, thank you. Is there any actual game changing bugs caused by this incompatibility besides the visual? Also sorry for this late reply, went to sleep late and then worked. Would you still like the export of my modpack?

**Comment by pietro-lopes** [comment]
> Ah alright, thank you. Is there any actual game changing bugs caused by this incompatibility besides the visual?

On 1.20.1 people are reporting being an issue only in Multiplayer.
Probably not but still is confusing to see some recipe that was not supposed to have that amount of items.

> Would you still like the export of my modpack?

Yes, I do need to run tests with CraftTweaker, you can DM me or find me at Discord with @Uncandango on All The Mods discord.

**Comment by pietro-lopes** [comment]
Closing this as it will be part of the investigation on #5
