### ISSUE TITLE
Genetics: Resequenced memory leak has been fixed, and InventoryListener class no longer exists

### ISSUE THREAD

**Issue by unilock** [pietro-lopes/AllTheLeaks#6]
The memory leak in Genetics: Resequenced that AllTheLeaks fixes has been fixed, as of 3 days ago: https://github.com/Berry-Club/Genetics-Resequenced/issues/44

Additionally, the class AllTheLeaks references no longer exists, leading to a crash when the player is cloned or respawns: https://github.com/Berry-Club/Genetics-Resequenced/commit/72b70a36fdb6a8ee223005bd68c0ae0b87c3edac

**Comment by pietro-lopes** [comment]
Thanks for the reminder, I completely forgot to update, as I reported the issue and he promptly solved it.

**Comment by pietro-lopes** [comment]
It is being uploaded to CF at this moment on version 0.1.4.

Thanks again.
